name: Docker Image CI Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up .env file
      run: |
        echo "Loading environment variables from .env file"
        if [ -f .env ]; then
          export $(grep -v '^#' .env | xargs)
        else
          echo ".env file not found."
        fi 
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
    - name: install requirements
      run: |
        make install
    - name: run linting
      run: |
        make lint
    - run: echo "🍏 This job's status is ${{ job.status }}."
